### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by shapeh** [ellern/quickpay-sdk-dotnet#1]
Hej Martin

Det ser lovende ud med denne SDK, tak for det :)
Har du evt. et simpelt kodeeksempel hvordan SDK bruges?
- alle eksempler på Quickpays hjemmeside er desværre Ruby og PHP.

vh
Per

**Comment by ellern** [comment]
Hej. Jeg vil prøve at se om jeg kan få tid til at lave et par eksempler.

**Comment by ellern** [comment]
Her er den korte udgave. 

Du har først brug for at få fat i en QuickPayClient, den får du fat i således. De første 2 parameter er urls til hhv. API og Invoicing API, hvis de undlades bruges standard. Jeg er ved at opdatere så det ikke er nødvendigt fremadrettet.

```
var quickPayClient = new QuickPay.SDK.QuickPayClient(null, null, _apiKey, _privateKey, _userKey);

var variables = new Dictionary<string, string>
{
    { "userId", "et user id" }
};

// Oprettelse af subscription
// public Task<Subscription> Create(string orderId, string currency, string description, string descriptor, Dictionary<string, string> variables);

var subscription = await quickPayClient.Subscriptions.Create($"orderId", "DKK", "description", "descriptor", variables).ConfigureAwait(false);

// Oprettelse af link til en subscription
// public Task<PaymentLinkUrl> CreateOrUpdatePaymentLink(int subscriptionId, int amount, bool autoFee, string language, string paymentMethods, string continueUrl, string cancelUrl, string callbackUrl, bool framed);

var subscriptionLink = await quickPayClient.Subscriptions.CreateOrUpdatePaymentLink(subscription.Id, AMOUNT, false, "da", "paymentMethods", "ContinueUrl", "CancelUrl", "CallbackUrl", true).ConfigureAwait(false);
```

Jeg holder nuget pakken opdateret med nyeste kode herfra, den kan findes på:
https://www.nuget.org/packages/QuickPay.SDK/

**Comment by shapeh** [comment]
Hej igen,

Det er super! :) 
Jeg laver et eksempel for Payments og poster det når du har opdateret, men indtil videre giver dit eksempel fin mening. 

Vh
Per

**Comment by ellern** [comment]
Her er lige lidt mere ift betaling.

Oprettelse af betaling via card token:

```
var quickpayPayment = await quickpayClient.Payments.Create("DKK", "orderId", variables).ConfigureAwait(false);

var quickpayCardToken = await quickpayClient.Cards.CreateToken("cardId").ConfigureAwait(false);

var quickpayAuthorizeAndCapture = await quickpayClient.Payments.Authorize(quickpayPayment.Id, AMOUNT, quickpayCardToken.Token, true).ConfigureAwait(false);
```

Oprettelse af betaling via subscription:

```
var quickpayAuthorize = await quickpayClient.Subscriptions.Recurring(subscriptionId, "orderId", amount, false, false, "descriptor).ConfigureAwait(false);

var quickpayCapture = await quickpayClient.Payments.Capture(quickpayAuthorize.Id, amount).ConfigureAwait(false);
```

**Comment by ellern** [comment]
Så fik jeg oprettet en readme samt opdateret nuget med nyeste kode. Sig til hvis der er noget specifikt du ønsker eksempel på.

**Comment by shapeh** [comment]
Hej Martin

Jeg kom lidt væk fra koden grundet et andet projekt. 
Det er helt perfekt det du har lavet dér - super med readme og nuget - jeg siger mange tak :)

Vh
