### ISSUE TITLE
Update Subscription Example

### ISSUE THREAD

**Issue by Zndtonone** [ellern/quickpay-sdk-dotnet#3]
Hej Martin,

Genial SDK, tak for det :)

Jeg har fundet ud af hvordan man bruger den i de fleste tilfælde, men kan ikke finde ud af hvordan opdaterer en Subscription med QuickPayClient.Subscriptions.Update(para1, para2, para3).

Det er vel til at opdatere kort oplysningerne for en Subsciption?

Har du noget eksempel på det?

mvh
Rúni

**Comment by ellern** [comment]
Update funktionen er måske ikke så komplet som den burde være.

Som den er nu, kan du kun opdatere `description` samt `variables` som er gemt på din subscription.

Så den skal bruges på flg. måde:

```
QuickPayClient.Subscriptions.Update(123, "Beskrivelse", new Dictionary<string, string>
            {
                { "navn1", "værdi1" },
                { "navn2", "værdi2" },
                { "osv", "osv" }
            })
```

Hvad vil du gerne opdatere på en subscription, så kan jeg evt. opdatere SDK

**Comment by Zndtonone** [comment]
> Update funktionen er måske ikke så komplet som den burde være.
> 
> Som den er nu, kan du kun opdatere `description` samt `variables` som er gemt på din subscription.
> 
> Så den skal bruges på flg. måde:
> 
> ```
> QuickPayClient.Subscriptions.Update(123, "Beskrivelse", new Dictionary<string, string>
>             {
>                 { "navn1", "værdi1" },
>                 { "navn2", "værdi2" },
>                 { "osv", "osv" }
>             })
> ```
> 
> Hvad vil du gerne opdatere på en subscription, så kan jeg evt. opdatere SDK

**Comment by Zndtonone** [comment]
Jeg tænkte at bruge Update funktionen til at opdatere betalingskortet til en subscription, så at Subscription ID osv er det samme, men kort informationen opdateres.

Tænkte at Update funktionen leverede en PaymentLinkUrl, som man så kunne redirecte'e brugeren til QuickPay for at opdatere sin Subscription med et nyt betalingskort.

**Comment by ellern** [comment]
Jeg er faktisk ikke sikker på at QuickPay understøtter dette, de gør ihverfald ikke via `Update` - du kan evt. prøve at lave et nyt betalings link via `CreateOrUpdatePaymentLink` metoden og se om den tager i mod et nyt kort og gemmer på subscription.

**Comment by Zndtonone** [comment]
Ok, var selv ikke sikker på om det lad sig gøre. Prøvede nemlig først det med CreateOrUpdatePaymentLink metoden, men da sagde QP at den specifikke subscription allerede var authorized.
Så man bliver nok nød til at lave en metode der gør brug af delete og create metoden samtidig med at databasen tager sig af at holde det samme id osv.

**Comment by ellern** [comment]
Ved mine egne subscriptions har jeg en reference til QuickPays subscription id - og når der skiftes kort, så opdatere jeg bare den reference til det nye id - jeg gør som sådan ikke noget ved de gamle subscriptions hos QuickPay.
